let product = [{
        id: 1001,
        title: "Japanese Lesson",
        description: "Japanese lessons tought by <em>professional</em> Japanese speakers!",
        price: "£20",
        loc: "South London",
        spaces: 5,
        availablesp: 5,
        image: "assets/japanese.png",
        rating: 5
    },
    {
        id: 1002,
        title: "French Lesson",
        description: "French lessons tought by <em>professional</em> French speakers!",
        price: "£10",
        loc: "Central London",
        spaces: 5,
        availablesp: 5,
        image: "assets/french.png",
        rating: 3
    },
    {
        id: 1003,
        title: "Portuguese Lesson",
        description: "Portuguese lessons tought by <em>professional</em> Portuguese speakers!",
        price: "£15",
        loc: "East London",
        spaces: 5,
        availablesp: 5,
        image: "assets/port.png",
        rating: 4
    },
    {
        id: 1004,
        title: "English Lesson",
        description: "English lessons tought by <em>professional</em> English speakers!",
        price: "£5",
        loc: "North London",
        spaces: 5,
        availablesp: 5,
        image: "assets/eng.png",
        rating: 3
    },
    {
        id: 1005,
        title: "Spanish Lesson",
        description: "Spanish lessons tought by <em>professional</em> Spanish speakers!",
        price: "£15",
        loc: "East London",
        spaces: 5,
        availablesp: 5,
        image: "assets/spanish.png",
        rating: 4
    },
    {
        id: 1006,
        title: "German Lesson",
        description: "German lessons tought by <em>professional</em> German speakers!",
        price: "£25",
        loc: "West London",
        spaces: 5,
        availablesp: 5,
        image: "assets/german.png",
        rating: 4
    },
    {
        id: 1007,
        title: "Mandarin Lessons",
        description: "Mandarin lessons tought by <em>professional</em> Mandarin speakers!",
        price: "£20",
        loc: "Noth London",
        spaces: 5,
        availablesp: 5,
        image: "assets/mandarin.png",
        rating: 4
    },
    {
        id: 1008,
        title: "Swahili Lesson",
        description: "Swahili lessons tought by <em>professional</em> Swahili speakers!",
        price: "£30",
        loc: "North London",
        spaces: 5,
        availablesp: 5,
        image: "assets/swahi.png",
        rating: 3
    },
    {
        id: 1009,
        title: "Russian Lesson",
        description: "Russian lessons tought by <em>professional</em> Russian speakers!",
        price: "£25",
        loc: "South London",
        spaces: 5,
        availablesp: 5,
        image: "assets/russ.png",
        rating: 4
    },
    {
        id: 1010,
        title: "Arabic Lesson",
        description: "Arabic lessons tought by <em>professional</em> Arabic speakers!",
        price: "£20",
        loc: "East London",
        spaces: 5,
        availablesp: 5,
        image: "assets/arabic.png",
        rating: 3
    },
]